### ISSUE TITLE
Docker add support for 'latest' tag

### ISSUE THREAD

**Issue by pavolholes** [unixorn/ha-mqtt-discoverable-cli#35]
Hi, first of all thanks a lot for this project and the upstream ha-mqtt-discoverable.

Can we get support for the `latest` tag for the docker hub? That way we don't have to specify the tag at all and we'll get the latest updates when they come out.

```
failed to deploy a stack: ha-mqtt-discoverable Pulling ha-mqtt-discoverable Error Error response from daemon: manifest for unixorn/ha-mqtt-discoverable-cli:latest not found: manifest unknown: manifest unknown
```

Thanks a lot!

**Comment by unixorn** [comment]
Forgot to close this when I started updating `latest` as well as building images with the module version.
